version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: icods_password
    restart: always
    volumes:
      - /tmp/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  icods-api:
    build: .
    container_name: icods-api
    depends_on:
      - db
    restart: always
    env_file: .env
    networks:
      - default
    ports:
      - "3333:3333"
    expose:
      - "3333"
    command: npm run start
    links:
      - db
