version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: icods_password
    volumes:
      - /home/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .  
    depends_on:
      - db
    restart: always
    networks:
      - default
    ports:
      - "3333:3333"
    command: npm run dev:server
    links:
      - db