version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: icods_password
    volumes:
      - /home/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # app:
  #   image: icodstech/icods-api:latest
  #   depends_on:
  #     - db
  #   restart: always
  #   networks:
  #     - default
  #   ports:
  #     - "5000:5000"
  #   command: npm run start
  #   links:
  #     - db
volumes:
  postgres:
