version: "3"

services:
  icods-api:
    image: icodstech/icods-api:latest
    container_name: icods-api
    restart: always
    env_file: .env
    networks:
      - default
    ports:
      - "3333:3333"
    expose:
      - "3333"
    command: npm run start
