version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: icods_password
    restart: always
    volumes:
      - /home/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  icods-api:
    image: icodstech/icods-api:latest
    container_name: icods-api
    depends_on:
      - db
    restart: always
    env_file: .env
    networks:
      - default
    ports:
      - "3333:3333"
    expose:
      - "3333"
    command: npm run start
    links:
      - db
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - icods-api
    networks:
      - default

