version: '3'

services:
  name: api-icods
  db:
    image: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: icods_password
    volumes:
      - /home/pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  app:
    depends_on:
      - db
    build: .
    networks:
      - default
    ports:
      - '5000:5000'
    command: npm run dev:server
    links:
      - db
volumes:
  postgres:
