name: CI
on:
  push:
    branches:
      - feature/deploy-image-api
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set-up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Install Dependencies
        run: yarn install

      - name: Build API
        run: yarn build

    defaults:
      run:
        shell: bash
        working-directory: api

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/icods-teste

      - name: QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Docker Buildx
        uses: docker/setup-buildx-action@v1
    
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}

      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          tags: ${{ secrets.DOCKER_USERNAME }}/icods-teste:2021.06.15

    defaults:
      run:
        shell: bash
        working-directory: api
